"""empty message

Revision ID: f021f3df44c3
Revises: 
Create Date: 2017-06-11 08:47:34.456800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f021f3df44c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxiv', sa.Column('conclusion', sa.Text(collation=''), nullable=True))
    op.add_column('arxiv', sa.Column('introduction', sa.Text(collation=''), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxiv', 'introduction')
    op.drop_column('arxiv', 'conclusion')
    # ### end Alembic commands ###
